# vim ft=yaml
#
# Travis CI configuration

dist: trusty
sudo: false

language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: osx
      compiler: gcc

addons:
  apt:
    packages:
    - libmysqlclient-dev
    - libpq-dev
    - libaio-dev

services:
  - mysql
  - postgresql

before_install:
  - >
    case "${TRAVIS_OS_NAME:-linux}" in
    osx)
      # Workaround for https://github.com/Homebrew/legacy-homebrew/issues/43874
      # brew uninstall libtool
      # brew update --quiet
      # brew install libtool mysql
      brew install mysql

      # OS X requires servers to be started explicitly
      brew services start mysql

      # Avoid PostgreSQL upgrade woes, just reinstall the database
      brew uninstall --ignore-dependencies postgresql
      rm -rf /usr/local/var/postgres
      brew install postgresql

      echo "Starting PostgreSQL"
      pg_ctl -wD /usr/local/var/postgres start
      echo "Creating user postgres"
      createuser -s postgres
      ;;
    esac

install:
  - pip install --user cram urllib3[secure] cpp-coveralls
  - >
    case "${TRAVIS_OS_NAME:-linux}" in
    osx)
      # OS X requires this for user-local pip packages
      export PATH=~/Library/Python/2.7/bin:$PATH
      ;;
    esac

before_script:
  - mysql -u root -e 'CREATE DATABASE sbtest'
  - psql -U postgres -c 'CREATE DATABASE sbtest'

script:
  - ./autogen.sh && ./configure --enable-coverage --enable-asan --enable-msan --with-mysql --with-pgsql
  - make
  - make distcheck
  - SBTEST_MYSQL_ARGS="--mysql-user=root" SBTEST_PGSQL_ARGS="--pgsql-user=postgres" make test

after_success:
  - coveralls --exclude third_party/ --gcov-options '\-lp'

# Local variables:
# mode: yaml
# End:
