language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - libmysqlclient-dev

before_install:
  - >
    case "${TRAVIS_OS_NAME:-linux}" in
    osx)
      brew update --quiet
      brew install mysql
      ;;
    esac

script: true
