name: sysbench
version: 1.0.0
summary: Cross-platform and multi-threaded benchmark tool
description: |
 sysbench is a modular, cross-platform and multi-threaded benchmark tool for
 evaluating OS parameters that are important for a system running a database
 under intensive load.

 The idea of this benchmark suite is to quickly get an impression about system
 performance without setting up complex database benchmarks or even without
 installing a database at all.

 Current features allow to test the following system parameters:
  * file I/O performance
  * scheduler performance
  * memory allocation and transfer speed
  * POSIX threads implementation performance
  * database server performance (OLTP benchmark)
grade: stable
confinement: classic

apps:
  sysbench:
    command: sysbench
    plugs:
      - network

parts:
  sysbench:
    source: .
    plugin: autotools
    build-packages:
      - libmysqlclient-dev
    stage-packages:
      - libmysqlclient20
      - libaio1
